import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job

args = getResolvedOptions(sys.argv, ["JOB_NAME", "SOURCE_DATABASE", "DESTINATION_BUCKET"])

sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args["JOB_NAME"], args)

# Read the table created by the Crawler in the Data Catalog
datasource = glueContext.create_dynamic_frame.from_catalog(
    database=args["SOURCE_DATABASE"],
    table_name="orders",  # table name generated by the crawler on the /orders/ folder
)

# Drop any residual null fields
cleaned_data = DropNullFields.apply(frame=datasource)

# Write to the final S3 bucket in CSV format
glueContext.write_dynamic_frame.from_options(
    frame=cleaned_data,
    connection_type="s3",
    connection_options={"path": f"s3://{args['DESTINATION_BUCKET']}/final_output/"},
    format="csv",
    format_options={
        "writeHeader": True,
        "separator": ",",
    },
)

job.commit()
